use lalrpop_util::lalrpop_mod;

pub mod lexer;
pub mod ast;
pub mod typed_ast;
pub mod symbol_table;
pub mod analyzer;
pub mod codegen;
pub mod formatter;
pub mod loader;
lalrpop_mod!(pub parser);

/// Embedded standard-library assets (unit name, Pascal source, compiled `.a`
/// archive), generated by `build.rs` into `OUT_DIR/libs.rs`.
pub mod stdlib_assets {
    include!(concat!(env!("OUT_DIR"), "/libs.rs"));
}

pub use analyzer::{SemanticAnalyzer, Diagnostic};
pub use ast::{CompilationUnit, Program, Unit};
pub use symbol_table::{SymbolTable, SymbolKind, SymbolId};
