[package]
name = "pascalmls"
version = "0.1.0"
edition = "2021"

[dependencies]
pascalm = { git = "https://github.com/omurilo/pascalm?ref=feat/port_to_rust", package = "pascalm" }
tokio = { version = "1.52.3", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"] }
tower-lsp = "0.20.0"
dashmap = "6.2.1"
crop = "0.4.3"
log = "0.4.31"
anyhow = "1.0.102"

# [[bin]]
# name = "pascalmls"
# path = "src/client.rs"

[[bin]]
name = "pascalmls"
path = "src/server.rs"
